select * from customer limit20
#
--Q1. What is the total revenue generated by male vs. female customers?
select gender,SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select 
customer_id,
purchase_amount,
discount_applied
from customer
where discount_applied='Yes' and purchase_amount > (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,ROUND(AVG(review_rating::numeric),2) AS "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,AVG(purchase_amount)
where 
grou
--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
--Q8. What are the top 3 most purchased products within each category? 
--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
--Q10. What is the revenue contribution of each age group? 